Repository JaneliaSciComp/fileglancer, pull requests merged in 2025-03, with the labels that each got.

#18 Proxy API for file share paths
  README.md
  fileglancer/__init__.py
  fileglancer/handlers.py
  fileglancer/tests/test_handlers.py
  src/index.ts
Labels: enhancement

#17 Adds navbar across pages; converts FileList to material-tailwind
  README.md
  jest.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/components/FileList.tsx
  src/components/Files.tsx
  src/components/Help.tsx
  src/components/Home.tsx
  src/components/Jobs.tsx
  src/components/TestComponent.tsx
  src/components/Toggle.tsx
  src/components/file-list/FileListCrumbs.tsx
  src/components/ui/CustomCheckbox.tsx
  src/components/ui/FileList.tsx
  src/components/ui/FileListCrumbs.tsx
  src/components/ui/Navbar.tsx
  src/hooks/useFileList.tsx
  src/layouts/MainLayout.tsx
  style/tailwind_converted.css
  tailwind.config.js
  tailwind.config.ts
  tsconfig.json
Labels: enhancement

#19 API for browsing file shares
  fileglancer/handlers.py
  fileglancer/paths.py
  fileglancer/tests/test_handlers.py
  fileglancer/tests/test_mock_server.py
  pixi.lock
  pyproject.toml
  src/handler.ts
  src/index.ts
Labels: enhancement

#20 chore: Updates pyproject.toml to build on linux-64
  pixi.lock
  pyproject.toml
Labels: enhancement

#21 File browser UI
  package-lock.json
  package.json
  pixi.lock
  src/App.tsx
  src/components/Files.tsx
  src/components/ui/CustomCheckbox.tsx
  src/components/ui/FileList.tsx
  src/components/ui/FileListCrumbs.tsx
  src/components/ui/FileSidebar.tsx
  src/handler.ts
  src/hooks/useFileBrowser.tsx
  src/hooks/useFileList.tsx
  src/index.ts
  src/layouts/MainLayout.tsx
  style/tailwind_converted.css
  tsconfig.json
Labels: enhancement

#22 fix: Adds UI routes for juypterhub access.
  package-lock.json
  package.json
  src/App.tsx
  src/components/ui/Navbar.tsx
  src/hooks/useFileBrowser.tsx
Labels: bug, enhancement

#27 Build refactoring
  .github/workflows/build.yml
  .gitignore
  README.md
  clean.sh
  package-lock.json
  package.json
  pixi.lock
  pyproject.toml
  style/tailwind_converted.css
Labels: bug

#30 Add API proxies for preferences and tickets
  fileglancer/filestore.py
  fileglancer/handlers.py
  fileglancer/paths.py
  fileglancer/tests/test_filestore.py
  fileglancer/tests/test_handlers.py
  jest.config.js
  src/handler.ts
  src/index.ts
  tsconfig.json
Labels: enhancement
